#!/usr/bin/env bash
#
# A Bash application that monitors the renewal of Let's Encrypt certificates
# and uploads the updated certificates to Hashicorp Vault.
# Ensure your certificates are always up-to-date and securely stored with automated synchronization.
#
# Dependencies:
# - vault
#
# License: MIT
# Author; Kirill Shtrykov <kirill@shtykov.com>
# Date: 2024-08-02

# Disable D-Bus to remove Vault warnings
export DBUS_SESSION_BUS_ADDRESS=/dev/null

# Logging function
log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') $@"
}

# Error function
error() {
    echo >&2 "$(date '+%Y-%m-%d %H:%M:%S') Error: $@"
    exit 1
}

log "Let's hide!"

# Check vault is present
which vault &>/dev/null || error "vault not found"

# Check certificates directory path variable
[[ -z "${CERT_DIR}" ]] && error "CERT_DIR environment variable doesn't set"

log "Certificate ${CERT_DIR}"

CERT=$CERT_DIR/cert.pem
PRIVKEY=$CERT_DIR/privkey.pem
CHAIN=$CERT_DIR/chain.pem
FULLCHAIN=$CERT_DIR/fullchain.pem

# Check certificate 
[[ -f "${CERT}" ]] || error "'${CERT}' not found"

# Check private key 
[[ -f "${PRIVKEY}" ]] || error "'${PRIVKEY}' not found"

# Check chain 
[[ -f "${CHAIN}" ]] || error "'${CHAIN}' not found"

# Check fullchain 
[[ -f "${FULLCHAIN}" ]] || error "'${FULLCHAIN}' not found"

# Check Vault token variable
[[ -z "${VAULT_TOKEN}" ]] && error "VAULT_TOKEN environment variable doesn't set"

# Try to renew vault token
log "Renew token"
vault token renew &> /dev/null

SECONDS=86400 # 24h
CURTIME=$(date +%s)
CERTTIME=$(stat $CERT -c %Y)
TIMEDIFF=$(expr $CURTIME - $CERTTIME)

if [ $TIMEDIFF -lt $SECONDS ]; then
    log "Upload certificates to Vault"
    vault kv put -mount=${VAULT_MOUNT:-kv} ${VAULT_PATH:-ssl} cert=@"${CERT}" privkey=@"${PRIVKEY}" chain=@"${CHAIN}" fullchain=@"${FULLCHAIN}"
else
    log "Certificates not renewed"
fi
